export const AVAILABLE_METRICS = [
    'total_overcommitted_burst',
    'total_granted_burst',
    'total_requested_burst',
    'total_interfered_burst',
    'total_power_draw',
    'mean_cpu_usage',
    'mean_cpu_demand',
    'mean_num_deployed_images',
    'max_num_deployed_images',
    'total_failure_vm_slices',
    'total_vms_submitted',
    'total_vms_queued',
    'total_vms_finished',
    'total_vms_failed',
]

export const METRIC_NAMES = {
    total_overcommitted_burst: 'Overcomm. CPU Cycles [MFLOP]',
    total_granted_burst: 'Granted CPU Cycles [MFLOP]',
    total_requested_burst: 'Requested CPU Cycles [MFLOP]',
    total_interfered_burst: 'Interfered CPU Cycles [MFLOP]',
    total_power_draw: 'Total Power Consumption [Wh]',
    mean_cpu_usage: 'Mean Host CPU Usage [MHz]',
    mean_cpu_demand: 'Mean Host CPU Demand [MHz]',
    mean_num_deployed_images: 'Mean Num. Deployed Images Per Host',
    max_num_deployed_images: 'Max. Num. Deployed Images Per Host',
    total_failure_vm_slices: 'Total Num. Failed VM Slices',
    total_vms_submitted: 'Total Num. VMs Submitted',
    total_vms_queued: 'Max. Num. VMs Queued',
    total_vms_finished: 'Max. Num. VMs Finished',
    total_vms_failed: 'Max. Num. VMs Failed',
}
