services:
  server:
    image: atlargeresearch/opendc:v2.4k
    restart: on-failure
    networks:
      - backend
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./traces
        target: /opt/opendc/traces
    environment:
      QUARKUS_OPENDC_UI_AUTH_DOMAIN: ${OPENDC_AUTH0_DOMAIN}
      QUARKUS_OPENDC_UI_AUTH_CLIENT_ID: ${OPENDC_AUTH0_CLIENT_ID}
      QUARKUS_OPENDC_UI_AUTH_AUDIENCE: ${OPENDC_AUTH0_AUDIENCE}
      QUARKUS_OIDC_APPLICATION_TYPE: service
      QUARKUS_OIDC_TOKEN_AUDIENCE: ${OPENDC_AUTH0_AUDIENCE}
      OPENDC_AUTH0_CLIENT_ID: ${OPENDC_AUTH0_CLIENT_ID}
      OPENDC_DB_USERNAME: ${OPENDC_DB_USERNAME:?No database username specified}
      OPENDC_DB_PASSWORD: ${OPENDC_DB_PASSWORD:?No database password specified}
      OPENDC_DB_URL: jdbc:postgresql://postgres:5432/opendc
      OPENDC_AUTH0_DOMAIN: ${OPENDC_AUTH0_DOMAIN:?No Auth0 domain specified}
      OPENDC_AUTH0_AUDIENCE: ${OPENDC_AUTH0_AUDIENCE:?No Auth0 audience specified}
      OPENDC_API_URL: ${OPENDC_API_BASE_URL:-http://web:8080}
      SENTRY_DSN: ${OPENDC_SERVER_SENTRY_DSN-}

  postgres:
    image: postgres:17.9
    restart: on-failure
    environment:
      POSTGRES_USER: ${OPENDC_DB_USERNAME}
      POSTGRES_PASSWORD: ${OPENDC_DB_PASSWORD}
    networks:
      - backend
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

networks:
  backend: {}
